# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'bcrypt'
gem 'bootsnap', require: false
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.2'
gem 'sqlite3', '~> 1.4'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'byebug'
end

gem 'auth_rails', path: '../..'
